module.exports.activities = [
  'Beach Hopping',
  'City Sightseeing',
  'Free Tour',
  'Mountain Trek',
  'Food Tasting Tour',
  'Scenic Drive',
  'Island Hopping',
  'Historical Tour',
  'Helicopter Ride',
  'Paragliding',
  'Skydiving',
  'Wine Tasting',
  'Cheese Tasting',
  'Museum',
  'Surfing',
  'Snowboarding',
  'Sandboarding',
  'Escape Room',
  'Cooking Lesson with Pro Chef',
  'Chocolate Making',
  'Chakra Massage',
  'Goat Yoga',
  'Petting Zoo',
  'Traditional Cooking Class',
  'Hot Air Balloon Ride',
  'Whale Watching',
  'Snorkeling',
  'Bungee Jumping',
  'Kayaking',
  'Horseback Riding',
  'Zip-lining',
  'Segway Tour',
  'Jet Ski',
  'Coffee Tasting',
  'Paddleboarding',
  'Haunted House',
  'Archery',
  'Shooting Range',
  'Snowshoe Tour',
  'Rock Climbing',
  'Tea Tasting',
  'Capybara Petting',
];
